[package]
name = "rust-axum"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.8"
http-body = "1.0.1"
http-body-util = "0.1.3"
serde = "1.0.228"
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["rt-multi-thread", "macros"] }
tower = "0.5.3"

